"""Generate language bindings from the two canonical shared sources.

Per ADR-0004, `shared/schema/` is the source of truth for the wire format. Per
ADR-0005, `shared/spec/` is the source of truth for the model facts a JSON
Schema cannot express -- gate signatures, violation codes, and the current
model version. Bindings for both are generated into each consuming project.
This script is the single definition of how that generation happens, so a
developer and CI run exactly the same command.

Usage, from the repository root:

    python shared/generate_bindings.py            # regenerate in place
    python shared/generate_bindings.py --check    # fail if output is stale

`--check` is what CI runs. It reports stale output rather than silently
correcting it, and leaves the working tree exactly as it found it.

The schema is generated by third-party tools; the spec is emitted by this
script, because those tools generate types from schemas rather than constants
from data. Both paths share the formatting and newline handling below, for the
reasons documented there.

This script invokes each project's toolchain; it does not import from either,
which would violate the dependency rule in shared/README.md.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from functools import partial
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "shared" / "schema" / "circuit.schema.json"
SPEC = ROOT / "shared" / "spec" / "circuit.spec.json"

MODELS = ROOT / "backend" / "src" / "phasor_workbench" / "models"
MODEL = ROOT / "frontend" / "src" / "model"

PYTHON_OUTPUT = MODELS / "circuit.py"
TYPESCRIPT_OUTPUT = MODEL / "circuit.ts"
PYTHON_SPEC_OUTPUT = MODELS / "spec.py"
TYPESCRIPT_SPEC_OUTPUT = MODEL / "spec.ts"

# Every flag here is load-bearing; see ADR-0004 and the notes in the schema.
#   --collapse-root-models + unconstrained IdentifierRef  -> list[str], not
#       list[RootModel[str]], which is unhashable and breaks referential checks
#   --snake-case-field  -> satisfies ruff's N815 while aliases preserve the
#       camelCase wire format
#   --strict-nullable   -> a field with a default is `list[str] = []`, not
#       `list[str] | None = []`, so no consumer handles null
#   --formatters ruff-check ruff-format -> output matches the project's own
#       toolchain, so `ruff check` and `ruff format --check` both pass. Both
#       passes are needed: ruff-format does not sort imports (I001) and
#       ruff-check does not format.
PYTHON_ARGS = [
    "--input-file-type", "jsonschema",
    "--output-model-type", "pydantic_v2.BaseModel",
    "--target-python-version", "3.11",
    "--use-annotated",
    "--use-standard-collections",
    "--use-union-operator",
    "--collapse-root-models",
    "--snake-case-field",
    "--strict-nullable",
    "--use-schema-description",
    "--use-field-description",
    "--disable-timestamp",
    "--formatters", "ruff-check", "ruff-format",
]

TYPESCRIPT_ARGS = ["--additionalProperties", "false", "--bannerComment", ""]


_WINDOWS = sys.platform == "win32"


def _resolve(local: Path, name: str, install_hint: str) -> str:
    """Prefer the project-local executable, fall back to PATH.

    Local development runs out of backend/.venv and frontend/node_modules; CI
    installs into the runner's own environment and has neither, so a hardcoded
    project-local path would fail there.
    """
    if local.is_file():
        return str(local)
    found = shutil.which(name)
    if found is not None:
        return found
    sys.exit(f"{name} not found. Install it with: {install_hint}")


def _venv_bin(name: str) -> str:
    scripts = ROOT / "backend" / ".venv" / ("Scripts" if _WINDOWS else "bin")
    local = scripts / f"{name}{'.exe' if _WINDOWS else ''}"
    return _resolve(local, name, 'pip install -e "./backend[dev]"')


def _node_bin(name: str) -> str:
    local = ROOT / "frontend" / "node_modules" / ".bin" / f"{name}{'.cmd' if _WINDOWS else ''}"
    return _resolve(local, name, "npm ci --prefix frontend")


def _run(command: list[str]) -> None:
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(
            f"Generation failed:\n  {' '.join(command)}\n\n"
            f"{result.stdout}\n{result.stderr}"
        )


def _normalize_newlines(path: Path) -> None:
    """Force LF, which .gitattributes requires and the generators disagree on.

    datamodel-code-generator writes CRLF on Windows while json2ts writes LF.
    Left alone, the committed bytes would depend on which platform generated
    them, and --check would compare CRLF against LF and report stale forever.
    """
    content = path.read_bytes()
    normalized = content.replace(b"\r\n", b"\n")
    if normalized != content:
        path.write_bytes(normalized)


def generate_python(output: Path) -> None:
    _run([_venv_bin("datamodel-codegen"), "--input", str(SCHEMA),
          "--output", str(output), *PYTHON_ARGS])
    _normalize_newlines(output)


def generate_typescript(output: Path) -> None:
    _run([_node_bin("json2ts"), "--input", str(SCHEMA),
          "--output", str(output), *TYPESCRIPT_ARGS])
    # json2ts does not read the project's Prettier config, so `format:check`
    # would reject its output. Formatting here mirrors the Python side, which
    # generates through ruff for the same reason.
    _run([_node_bin("prettier"), "--write", "--log-level", "warn", str(output)])
    _normalize_newlines(output)


# --- The spec (ADR-0005, ADR-0006) ---------------------------------------

# The stage that produces a violation. Fixed rather than inferred from the spec,
# because a typo in a phase name should fail generation instead of quietly
# creating a fourth phase that nothing selects.
PHASES = ("shape", "semantic", "load")


def _declarations(section: dict[str, Any]) -> dict[str, Any]:
    """Drop `$`-prefixed keys, which annotate the spec rather than declare in it.

    JSON has no comments and the schema already uses `$comment` this way, so the
    spec keeps its explanations beside the data they explain.
    """
    return {key: value for key, value in section.items() if not key.startswith("$")}


def load_spec() -> dict[str, Any]:
    """Read the spec, check it against the schema, and reject a malformed one.

    The cross-check is the reason this function exists. Adding a gate touches
    both shared sources, and forgetting either half has to fail here -- the
    alternative is shipping a gate that every validator rejects, or a signature
    for a gate no circuit can name.
    """
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))

    gates = _declarations(spec["gates"])
    violations = _declarations(spec["violations"])

    declared = set(schema["$defs"]["GateName"]["enum"])
    specified = set(gates)
    if declared != specified:
        sys.exit(
            "Gate names disagree between the two shared sources:\n"
            f"  in circuit.schema.json only: {sorted(declared - specified) or 'none'}\n"
            f"  in circuit.spec.json only:   {sorted(specified - declared) or 'none'}\n\n"
            "Adding or removing a gate means editing both files together."
        )

    for name, signature in gates.items():
        if set(signature) != {"targets", "controls", "parameters"}:
            sys.exit(f"Gate '{name}' must declare targets, controls, and parameters.")
        if signature["targets"] < 1:
            sys.exit(f"Gate '{name}' must act on at least one target qubit.")
        if signature["controls"] < 0:
            sys.exit(f"Gate '{name}' declares a negative control count.")
        parameters = signature["parameters"]
        if len(set(parameters)) != len(parameters):
            sys.exit(f"Gate '{name}' names a parameter more than once.")

    for code, violation in violations.items():
        if violation.get("severity") not in {"error", "warning"}:
            sys.exit(f"Violation '{code}' must declare severity 'error' or 'warning'.")
        # Per ADR-0006 every code names the phase that produces it, so each
        # consumer selects the codes it owns from data rather than from a list
        # hardcoded in two test suites.
        if violation.get("phase") not in PHASES:
            sys.exit(
                f"Violation '{code}' must declare a phase, one of "
                f"{', '.join(sorted(PHASES))}."
            )

    return {
        "schemaVersion": spec["schemaVersion"],
        "gates": gates,
        "violations": violations,
    }


def _python_tuple(values: list[str]) -> str:
    inner = ", ".join(f'"{value}"' for value in values)
    return f"({inner},)" if values else "()"


def _python_spec_source(spec: dict[str, Any]) -> str:
    warnings = [
        code
        for code, violation in spec["violations"].items()
        if violation["severity"] == "warning"
    ]
    lines = [
        "# generated by shared/generate_bindings.py",
        "#   source:  circuit.spec.json",
        "",
        '"""Model facts the JSON Schema cannot express. See ADR-0005.',
        "",
        "Generated from shared/spec/circuit.spec.json and never hand-edited. Each",
        "violation code's description lives there rather than here.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping",
        "from enum import StrEnum",
        "from types import MappingProxyType",
        "from typing import Final, NamedTuple",
        "",
        "from .circuit import GateName",
        "",
        "",
        "#: The model version this build writes. Migration policy: docs/CircuitModel.md.",
        f'SCHEMA_VERSION: Final = "{spec["schemaVersion"]}"',
        "",
        "",
        "class ViolationCode(StrEnum):",
        '    """What a validator may report. Fixtures name these codes verbatim."""',
        "",
    ]
    lines += [f'    {code} = "{code}"' for code in spec["violations"]]
    lines += [
        "",
        "",
        "class ViolationPhase(StrEnum):",
        '    """The stage that produces a code. See ADR-0006."""',
        "",
    ]
    lines += [f'    {phase.upper()} = "{phase}"' for phase in PHASES]
    lines += [
        "",
        "",
        "#: Each consumer selects the codes it owns from here, not from a hardcoded list.",
        "VIOLATION_PHASES: Final[Mapping[ViolationCode, ViolationPhase]] = MappingProxyType(",  # noqa: E501
        "    {",
    ]
    lines += [
        f"        ViolationCode.{code}: ViolationPhase.{violation['phase'].upper()},"
        for code, violation in spec["violations"].items()
    ]
    lines += [
        "    }",
        ")",
        "",
        "",
        "WARNING_CODES: Final[frozenset[ViolationCode]] = frozenset(",
        "    [",
    ]
    lines += [f"        ViolationCode.{code}," for code in warnings]
    lines += [
        "    ]",
        ")",
        "",
        "",
        "class GateSignature(NamedTuple):",
        '    """How many qubits a gate takes, and which parameters it requires."""',
        "",
        "    targets: int",
        "    controls: int",
        "    parameters: tuple[str, ...]",
        "",
        "",
        "GATE_SIGNATURES: Final[Mapping[GateName, GateSignature]] = MappingProxyType(",
        "    {",
    ]
    # Keyed by value rather than by member name, so a future gate whose name is
    # not a Python identifier still generates.
    lines += [
        f'        GateName("{name}"): GateSignature('
        f"targets={signature['targets']}, controls={signature['controls']}, "
        f"parameters={_python_tuple(signature['parameters'])}),"
        for name, signature in spec["gates"].items()
    ]
    lines += ["    }", ")", ""]
    return "\n".join(lines)


def _typescript_spec_source(spec: dict[str, Any]) -> str:
    warnings = [
        code
        for code, violation in spec["violations"].items()
        if violation["severity"] == "warning"
    ]
    lines = [
        "// generated by shared/generate_bindings.py",
        "//   source:  circuit.spec.json",
        "",
        "/**",
        " * Model facts the JSON Schema cannot express. See ADR-0005.",
        " *",
        " * Generated from shared/spec/circuit.spec.json and never hand-edited. Each",
        " * violation code's description lives there rather than here.",
        " */",
        "",
        "import type { GateName } from './circuit';",
        "",
        "/** The model version this build writes. Migration policy: docs/CircuitModel.md. */",
        f"export const SCHEMA_VERSION = '{spec['schemaVersion']}';",
        "",
        "/** What a validator may report. Fixtures name these codes verbatim. */",
        "export type ViolationCode =",
    ]
    lines += [f"  | '{code}'" for code in spec["violations"]]
    lines[-1] += ";"
    lines += [
        "",
        "export const VIOLATION_CODES: readonly ViolationCode[] = [",
    ]
    lines += [f"  '{code}'," for code in spec["violations"]]
    lines += [
        "];",
        "",
        "/** The stage that produces a code. See ADR-0006. */",
        "export type ViolationPhase =",
    ]
    lines += [f"  | '{phase}'" for phase in PHASES]
    lines[-1] += ";"
    lines += [
        "",
        "/**",
        " * Each consumer selects the codes it owns from here, not from a hardcoded list.",
        " *",
        " * Every ViolationCode must appear, or this file fails to type-check.",
        " */",
        "export const VIOLATION_PHASES: Readonly<",
        "  Record<ViolationCode, ViolationPhase>",
        "> = {",
    ]
    lines += [
        f"  '{code}': '{violation['phase']}',"
        for code, violation in spec["violations"].items()
    ]
    lines += [
        "};",
        "",
        "export const WARNING_CODES: readonly ViolationCode[] = [",
    ]
    lines += [f"  '{code}'," for code in warnings]
    lines += [
        "];",
        "",
        "/** How many qubits a gate takes, and which parameters it requires. */",
        "export interface GateSignature {",
        "  readonly targets: number;",
        "  readonly controls: number;",
        "  readonly parameters: readonly string[];",
        "}",
        "",
        "/** Every GateName must appear here, or this file fails to type-check. */",
        "export const GATE_SIGNATURES: Readonly<Record<GateName, GateSignature>> = {",
    ]
    # Keys are quoted unconditionally and unquoted by Prettier where it can, so
    # a future gate name needing quotes generates without special handling.
    lines += [
        f"  '{name}': {{ targets: {signature['targets']}, "
        f"controls: {signature['controls']}, "
        f"parameters: {json.dumps(signature['parameters'])} }},"
        for name, signature in spec["gates"].items()
    ]
    lines += ["};", ""]
    return "\n".join(lines)


def generate_python_spec(spec: dict[str, Any], output: Path) -> None:
    output.write_text(_python_spec_source(spec), encoding="utf-8", newline="\n")
    # Both passes, for the same reason the schema side passes both to
    # datamodel-codegen: ruff-format does not sort imports and ruff check does
    # not format. `--fix` is what makes the output canonical rather than
    # merely acceptable, so --check compares equal run to run.
    _run([_venv_bin("ruff"), "check", "--quiet", "--fix", str(output)])
    _run([_venv_bin("ruff"), "format", "--quiet", str(output)])
    _normalize_newlines(output)


def generate_typescript_spec(spec: dict[str, Any], output: Path) -> None:
    output.write_text(_typescript_spec_source(spec), encoding="utf-8", newline="\n")
    _run([_node_bin("prettier"), "--write", "--log-level", "warn", str(output)])
    _normalize_newlines(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed output differs from freshly generated output",
    )
    args = parser.parse_args()

    for source in (SCHEMA, SPEC):
        if not source.is_file():
            sys.exit(f"Shared source not found: {source}")

    # Loaded before anything is written, so a spec that disagrees with the
    # schema fails without leaving half-regenerated output behind.
    spec = load_spec()

    targets = [
        (generate_python, PYTHON_OUTPUT),
        (generate_typescript, TYPESCRIPT_OUTPUT),
        (partial(generate_python_spec, spec), PYTHON_SPEC_OUTPUT),
        (partial(generate_typescript_spec, spec), TYPESCRIPT_SPEC_OUTPUT),
    ]

    if not args.check:
        for generate, output in targets:
            output.parent.mkdir(parents=True, exist_ok=True)
            generate(output)
            print(f"generated {output.relative_to(ROOT)}")
        return 0

    # Regenerate in place and restore, rather than generating into a temporary
    # directory. Both formatters resolve their configuration by walking up from
    # the file being written, so a candidate outside the project tree is
    # formatted differently and would always compare unequal.
    stale: list[Path] = []
    for generate, output in targets:
        original = output.read_bytes() if output.is_file() else None
        try:
            generate(output)
            if output.read_bytes() != original:
                stale.append(output)
        finally:
            if original is not None:
                output.write_bytes(original)
            elif output.is_file():
                output.unlink()

    if stale:
        listing = "\n".join(f"  {p.relative_to(ROOT)}" for p in stale)
        sys.exit(
            "Generated bindings are stale:\n"
            f"{listing}\n\n"
            "The schema and its regenerated output belong in the same commit.\n"
            "Run: python shared/generate_bindings.py"
        )

    print("generated bindings are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
